# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/ds/dsa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/ds/dsa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ds/dsa/CMakeFiles /root/ds/dsa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ds/dsa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dsa

# Build rule for target.
dsa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dsa
.PHONY : dsa

# fast build rule for target.
dsa/fast:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/build
.PHONY : dsa/fast

src/Hashes.o: src/Hashes.c.o

.PHONY : src/Hashes.o

# target to build an object file
src/Hashes.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/Hashes.c.o
.PHONY : src/Hashes.c.o

src/Hashes.i: src/Hashes.c.i

.PHONY : src/Hashes.i

# target to preprocess a source file
src/Hashes.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/Hashes.c.i
.PHONY : src/Hashes.c.i

src/Hashes.s: src/Hashes.c.s

.PHONY : src/Hashes.s

# target to generate assembly for a file
src/Hashes.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/Hashes.c.s
.PHONY : src/Hashes.c.s

src/avltree.o: src/avltree.c.o

.PHONY : src/avltree.o

# target to build an object file
src/avltree.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/avltree.c.o
.PHONY : src/avltree.c.o

src/avltree.i: src/avltree.c.i

.PHONY : src/avltree.i

# target to preprocess a source file
src/avltree.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/avltree.c.i
.PHONY : src/avltree.c.i

src/avltree.s: src/avltree.c.s

.PHONY : src/avltree.s

# target to generate assembly for a file
src/avltree.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/avltree.c.s
.PHONY : src/avltree.c.s

src/common.o: src/common.c.o

.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i

.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s

.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/common.c.s
.PHONY : src/common.c.s

src/hashmap.o: src/hashmap.c.o

.PHONY : src/hashmap.o

# target to build an object file
src/hashmap.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/hashmap.c.o
.PHONY : src/hashmap.c.o

src/hashmap.i: src/hashmap.c.i

.PHONY : src/hashmap.i

# target to preprocess a source file
src/hashmap.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/hashmap.c.i
.PHONY : src/hashmap.c.i

src/hashmap.s: src/hashmap.c.s

.PHONY : src/hashmap.s

# target to generate assembly for a file
src/hashmap.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/hashmap.c.s
.PHONY : src/hashmap.c.s

src/heapsort.o: src/heapsort.c.o

.PHONY : src/heapsort.o

# target to build an object file
src/heapsort.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/heapsort.c.o
.PHONY : src/heapsort.c.o

src/heapsort.i: src/heapsort.c.i

.PHONY : src/heapsort.i

# target to preprocess a source file
src/heapsort.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/heapsort.c.i
.PHONY : src/heapsort.c.i

src/heapsort.s: src/heapsort.c.s

.PHONY : src/heapsort.s

# target to generate assembly for a file
src/heapsort.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/heapsort.c.s
.PHONY : src/heapsort.c.s

src/llist.o: src/llist.c.o

.PHONY : src/llist.o

# target to build an object file
src/llist.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/llist.c.o
.PHONY : src/llist.c.o

src/llist.i: src/llist.c.i

.PHONY : src/llist.i

# target to preprocess a source file
src/llist.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/llist.c.i
.PHONY : src/llist.c.i

src/llist.s: src/llist.c.s

.PHONY : src/llist.s

# target to generate assembly for a file
src/llist.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/llist.c.s
.PHONY : src/llist.c.s

src/priorityqueue.o: src/priorityqueue.c.o

.PHONY : src/priorityqueue.o

# target to build an object file
src/priorityqueue.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/priorityqueue.c.o
.PHONY : src/priorityqueue.c.o

src/priorityqueue.i: src/priorityqueue.c.i

.PHONY : src/priorityqueue.i

# target to preprocess a source file
src/priorityqueue.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/priorityqueue.c.i
.PHONY : src/priorityqueue.c.i

src/priorityqueue.s: src/priorityqueue.c.s

.PHONY : src/priorityqueue.s

# target to generate assembly for a file
src/priorityqueue.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/priorityqueue.c.s
.PHONY : src/priorityqueue.c.s

src/queue.o: src/queue.c.o

.PHONY : src/queue.o

# target to build an object file
src/queue.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/queue.c.o
.PHONY : src/queue.c.o

src/queue.i: src/queue.c.i

.PHONY : src/queue.i

# target to preprocess a source file
src/queue.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/queue.c.i
.PHONY : src/queue.c.i

src/queue.s: src/queue.c.s

.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/queue.c.s
.PHONY : src/queue.c.s

src/search.o: src/search.c.o

.PHONY : src/search.o

# target to build an object file
src/search.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/search.c.o
.PHONY : src/search.c.o

src/search.i: src/search.c.i

.PHONY : src/search.i

# target to preprocess a source file
src/search.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/search.c.i
.PHONY : src/search.c.i

src/search.s: src/search.c.s

.PHONY : src/search.s

# target to generate assembly for a file
src/search.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/search.c.s
.PHONY : src/search.c.s

src/sort.o: src/sort.c.o

.PHONY : src/sort.o

# target to build an object file
src/sort.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/sort.c.o
.PHONY : src/sort.c.o

src/sort.i: src/sort.c.i

.PHONY : src/sort.i

# target to preprocess a source file
src/sort.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/sort.c.i
.PHONY : src/sort.c.i

src/sort.s: src/sort.c.s

.PHONY : src/sort.s

# target to generate assembly for a file
src/sort.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/sort.c.s
.PHONY : src/sort.c.s

src/stack.o: src/stack.c.o

.PHONY : src/stack.o

# target to build an object file
src/stack.c.o:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/stack.c.o
.PHONY : src/stack.c.o

src/stack.i: src/stack.c.i

.PHONY : src/stack.i

# target to preprocess a source file
src/stack.c.i:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/stack.c.i
.PHONY : src/stack.c.i

src/stack.s: src/stack.c.s

.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.c.s:
	$(MAKE) -f CMakeFiles/dsa.dir/build.make CMakeFiles/dsa.dir/src/stack.c.s
.PHONY : src/stack.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dsa"
	@echo "... edit_cache"
	@echo "... src/Hashes.o"
	@echo "... src/Hashes.i"
	@echo "... src/Hashes.s"
	@echo "... src/avltree.o"
	@echo "... src/avltree.i"
	@echo "... src/avltree.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/hashmap.o"
	@echo "... src/hashmap.i"
	@echo "... src/hashmap.s"
	@echo "... src/heapsort.o"
	@echo "... src/heapsort.i"
	@echo "... src/heapsort.s"
	@echo "... src/llist.o"
	@echo "... src/llist.i"
	@echo "... src/llist.s"
	@echo "... src/priorityqueue.o"
	@echo "... src/priorityqueue.i"
	@echo "... src/priorityqueue.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/search.o"
	@echo "... src/search.i"
	@echo "... src/search.s"
	@echo "... src/sort.o"
	@echo "... src/sort.i"
	@echo "... src/sort.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

